blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/dominik-eller/laravel-data-normalizer/discussions/new?category=q-a
    about: Ask the community for help
  - name: Request a feature
    url: https://github.com/dominik-eller/laravel-data-normalizer/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Report a security vulnerability
    url: https://github.com/dominik-eller/laravel-data-normalizer#security-vulnerabilities
    about: Please report security vulnerabilities by email to me@dominik-eller.de
